import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Halo from "@/components/TorchEffect/TorchEffect";
import TorchEffect from "@/components/TorchEffect/TorchEffect";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <TorchEffect />
          <Navbar />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
